"""Initial migration

Revision ID: 7f49304c664f
Revises: 
Create Date: 2026-01-04 08:01:06.361441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f49304c664f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chromosomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chromosomes_id'), 'chromosomes', ['id'], unique=False)
    op.create_index(op.f('ix_chromosomes_name'), 'chromosomes', ['name'], unique=True)
    op.create_table('genome_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=False),
    sa.Column('stat_value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genome_stats_id'), 'genome_stats', ['id'], unique=False)
    op.create_index(op.f('ix_genome_stats_stat_name'), 'genome_stats', ['stat_name'], unique=True)
    op.create_table('genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('gene_name', sa.String(), nullable=True),
    sa.Column('start_pos', sa.Integer(), nullable=False),
    sa.Column('end_pos', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=1), nullable=False),
    sa.Column('chromosome_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chromosome_id'], ['chromosomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_gene_id'), 'genes', ['gene_id'], unique=True)
    op.create_index(op.f('ix_genes_gene_name'), 'genes', ['gene_name'], unique=False)
    op.create_index(op.f('ix_genes_id'), 'genes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genes_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_gene_name'), table_name='genes')
    op.drop_index(op.f('ix_genes_gene_id'), table_name='genes')
    op.drop_table('genes')
    op.drop_index(op.f('ix_genome_stats_stat_name'), table_name='genome_stats')
    op.drop_index(op.f('ix_genome_stats_id'), table_name='genome_stats')
    op.drop_table('genome_stats')
    op.drop_index(op.f('ix_chromosomes_name'), table_name='chromosomes')
    op.drop_index(op.f('ix_chromosomes_id'), table_name='chromosomes')
    op.drop_table('chromosomes')
    # ### end Alembic commands ###
