"""Add sequence column to Chromosome table

Revision ID: 2ad9a30d1f9d
Revises: 7f49304c664f
Create Date: 2026-01-04 08:48:13.645296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad9a30d1f9d'
down_revision: Union[str, Sequence[str], None] = '7f49304c664f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chromosomes', sa.Column('sequence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chromosomes', 'sequence')
    # ### end Alembic commands ###
