# --- Snakefile ---

# --- Configuration ---

configfile: "config.yaml"

# --- Target ---

rule all:
    input:
        "analysis/stats/gc_content_per_chromosome.done",
        "analysis/stats/cpg_frequency_per_chromosome.done",
        "analysis/stats/nuclear_base_composition.done",
        "analysis/stats/dinucleotide_frequency.done",
        "analysis/stats/per_chromosome_composition.done"
    shell:
        "echo 'Pipeline complete. All statistics are in genome_guides.db'"

# --- Pipeline Steps ---

# Rule 1: Loading the raw FASTA sequences into the DB
rule load_sequences:
    input:
        fasta=config["fasta_file"],
        script="scripts/parse_fasta.py"
    output:
        db="genome_guides.db"
    shell:
        "python {input.script} && touch {output.db}"

# Rule 2: Loading the gene annotations (depends on the DB existing)
rule load_genes:
    input:
        gtf=config["gtf_file"],
        script="scripts/parse_gtf.py",
        db="genome_guides.db"
    output:
        # We 'touch' the DB again to update its timestamp
        touch("genome_guides.db")
    shell:
        "python {input.script}"

# Rule 3: Running all our analysis scripts
# This depends on the database being fully loaded
rule run_analysis:
    input:
        db="genome_guides.db",
        gc_script="analysis/calculate_gc_content.py",
        cpg_script="analysis/calculate_cpg_per_frequency.py",
        base_comp_script="analysis/calculate_base_composition.py",
        dinu_script="analysis/calculate_dinucleotides.py",
        per_chromo_script="analysis/calculate_per_chromosome_composition.py"
    output:
        touch("analysis/stats/gc_content_per_chromosome.done"),
        touch("analysis/stats/cpg_frequency_per_chromosome.done"),
        touch("analysis/stats/nuclear_base_composition.done"),
        touch("analysis/stats/dinucleotide_frequency.done"),
        touch("analysis/stats/per_chromosome_composition.done")
    shell:
        """
        python {input.gc_script}
        python {input.cpg_script}
        python {input.base_comp_script}
        python {input.dinu_script}
        python {input.per_chromo_script}
        """

# --- Cleanup  ---
rule clean:
    shell:
        "rm -f genome_guides.db analysis/stats/*.done"